### ISSUE TITLE
制作新数据集参数

### ISSUE THREAD

**Issue by lhy121** [nie-lang/UnsupervisedDeepImageStitching#7]
ImageAlignment/synthetic_dataset.py中将coco2014中的640480图片制作数据集时的参数是
box_size = 128
height = 360
width = 480
overlap_rate = 0.5
rho = int(box_size/5.0)
我想将我自己的数据集（19201080）图片制作数据集时的参数应该调为多少呢？
请教教，大佬

**Comment by FXY0117** [comment]
Excuse me, I see that the output image size is related to the box_size when making synthetic dataset. So I'm confused that what's the relationship between (height,width) and box_size. In other words, as said from the former one, how to set a (1920,1080）image's box_size, height and width respectively? I am looking forward to your solution.

**Comment by nie-lang** [comment]
The synthestic dataset sets

**Comment by nie-lang** [comment]
Fixing the size of box_size, the larger the (height,width) is,the smaller the content is. And be sure the (height,width) larger than (2.4\*box_size,2.4\*box_size) when using the synthetic_dataset.py.

In the process of generating a synthetic dataset, the program will resize the image to (height,width) resolution first, and then produce an image pair of (box_size,box_size) resolution from the resized image. So just define your own dataset parameters according to your demand.

For example, we set box_size to 128 because our homography model takes the 128*128 images as input. As for the (height,width), we only need to make sure it is larger than (2.4\*box_size,2.4\*box_size).

**Comment by FXY0117** [comment]
Ok, I understand it. Appreciating for your solution
